// pairing_compat_test.dart — Wire-compat test for the pairing handshake (Dart side).
//
// Spec: docs/specs/mobile-desktop-pairing.md § "Handshake protocol".
// Source of truth for the wire format.
//
// This test is the Dart mirror of
//   src-tauri/tests/pairing_crypto_compat_test.rs
//
// It pins the EXACT byte-for-byte wire format that the Rust side must
// produce/consume. The fixtures are the SAME values dumped from the Rust
// tests via MC_PAIRING_DUMP_FIXTURES=1 cargo test. If the Dart side
// computes the same session_secret from the same handshake response, the
// protocol is wire-compatible end-to-end.
//
// Without this test passing, the entire pairing protocol is a paper
// design and Phase 3 (mobile) should not ship.
//
// Fixture values were generated by:
//   MC_PAIRING_DUMP_FIXTURES=1 cargo test -p miracle-claw --test pairing_crypto_compat_test
//
// DO NOT EDIT the fixtures by hand. If they go stale, regenerate them
// with the command above and update this file.

import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:flutter_test/flutter_test.dart';

// ─────────────────────────────────────────────────────────────────────
// Fixture: phone's long-lived static keypair (the one persisted in
// flutter_secure_storage on the phone).
// ─────────────────────────────────────────────────────────────────────

const String phoneStaticPrivHex =
    '776f726b7320666978747572652d736565642d30303030303030303030303030';

const String phoneStaticPubHex =
    'c8e49b6f97fe3b94b2a3c51b7e5ea2c26716d725d1bbd7391e6917f12b1ffb2f';

const String sessionIdHex =
    '0102030405060708090a0b0c0d0e0f10';

const String sessionSecretHex =
    'aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899';

const String ephemeralPubB64 =
    '8lrSUaPPfp++HKeHQAjQDhc84+ZuMAC1n5MuQXXBvGM=';

const String encryptedSecretB64 =
    'z6UlOmAmYZftznlixuP0qFCMPft5p0NjyNbJ0jV2EowGm0saFxI9KUEoUSWWadJyPTjQMvwR8QYF6Kob';

const String hmacEmptyBodyB64 =
    '8XOy6tkvuoXgzkJEf93gMB+olDeGGIi1mOrcTkXZE64=';

/// Wire-format constant. Mirrors `PAIR_INFO` on the Rust side. **DO NOT
/// CHANGE without coordinating with the Rust side — breaking this is a
/// wire-incompat.**
const String pairInfo = 'miracle-claw-pair-v1';

// ─────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────

Uint8List _hexToBytes(String hex) {
  if (hex.length % 2 != 0) {
    throw FormatException('hex string must have even length, got ${hex.length}');
  }
  final bytes = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < bytes.length; i++) {
    bytes[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return bytes;
}

String _bytesToHex(Uint8List bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

/// Derive the X25519 public key from a private seed, using the same
/// library the Dart handshake code uses (`package:cryptography`).
///
/// On the Rust side this corresponds to `x25519_dalek::x25519(scalar,
/// X25519_BASEPOINT_BYTES)`. Both compute the standard X25519 scalar
/// multiplication per RFC 7748 §5.
Future<Uint8List> _derivePublicKey(Uint8List privateKey) async {
  final x25519 = X25519();
  final kp = await x25519.newKeyPairFromSeed(privateKey);
  final pk = await kp.extractPublicKey();
  return Uint8List.fromList(pk.bytes);
}

/// Phone side of the handshake: given the Rust-side response, derive
/// the same session_secret. Mirrors `phone_decrypt_handshake` on the
/// Rust side.
Future<Uint8List> _phoneDecryptHandshake({
  required Uint8List phoneStaticPriv,
  required Uint8List sessionId,
  required Uint8List ephemeralPub,
  required Uint8List encryptedSecret,
}) async {
  // Step 1: X25519 DH → shared_secret
  final x25519 = X25519();
  final phoneKp = await x25519.newKeyPairFromSeed(phoneStaticPriv);
  final sharedSecret = await x25519.sharedSecretKey(
    keyPair: phoneKp,
    remotePublicKey: SimplePublicKey(
      ephemeralPub,
      type: KeyPairType.x25519,
    ),
  );

  // Step 2: HKDF-SHA256(salt=session_id, ikm=shared_secret, info=PAIR_INFO, L=32)
  final hkdf = Hkdf(hmac: Hmac.sha256(), outputLength: 32);
  final sessionKey = await hkdf.deriveKey(
    secretKey: sharedSecret,
    nonce: sessionId, // HKDF salt
    info: utf8.encode(pairInfo),
  );

  // Step 3: AES-256-GCM decrypt
  // Wire format: nonce(12) || ciphertext || tag(16)
  final nonce = encryptedSecret.sublist(0, 12);
  final ciphertextWithTag = encryptedSecret.sublist(12);

  // cryptography package's AesGcm.expectTagLength handles the trailing tag.
  final aes = AesGcm.with256bits();
  final box = SecretBox(
    ciphertextWithTag.sublist(0, ciphertextWithTag.length - 16),
    nonce: nonce,
    mac: Mac(ciphertextWithTag.sublist(ciphertextWithTag.length - 16)),
  );
  final plaintext = await aes.decrypt(box, secretKey: sessionKey);
  return Uint8List.fromList(plaintext);
}

// ─────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────

void main() {
  test('phone_static_pub matches derived from private', () async {
    final priv = _hexToBytes(phoneStaticPrivHex);
    final expectedPub = _hexToBytes(phoneStaticPubHex);
    final derivedPub = await _derivePublicKey(priv);
    expect(
      _bytesToHex(derivedPub),
      phoneStaticPubHex,
      reason: 'phoneStaticPubHex fixture is out of date. The '
          'package:cryptography X25519 implementation should produce '
          'the same bytes as x25519-dalek 2.0.1. If they differ after '
          'a dependency bump, regenerate via the Rust fixture-dump '
          'command (see file header).',
    );
    expect(derivedPub, expectedPub);
  });

  test('decrypt Rust-produced handshake → same session_secret', () async {
    final priv = _hexToBytes(phoneStaticPrivHex);
    final sessionId = _hexToBytes(sessionIdHex);
    final ephemeralPub = base64Decode(ephemeralPubB64);
    final encryptedSecret = base64Decode(encryptedSecretB64);

    final recovered = await _phoneDecryptHandshake(
      phoneStaticPriv: priv,
      sessionId: sessionId,
      ephemeralPub: Uint8List.fromList(ephemeralPub),
      encryptedSecret: Uint8List.fromList(encryptedSecret),
    );

    expect(
      _bytesToHex(recovered),
      sessionSecretHex,
      reason: 'Dart side must derive the SAME session_secret that the '
          'Rust side encrypted. If this fails after a dependency bump, '
          're-run the Rust fixture-dump command and update both '
          'fixture files.',
    );
  });

  test('wire format: nonce(12) + ciphertext(32) + tag(16) = 60 bytes', () {
    final encryptedSecret = base64Decode(encryptedSecretB64);
    expect(
      encryptedSecret.length,
      60,
      reason: 'A 32-byte session_secret with 12-byte nonce + 16-byte tag '
          'is exactly 60 bytes on the wire. Anything else is a '
          'wire-incompat.',
    );
  });

  test('ephemeral_pub decodes to 32 bytes', () {
    final ephemeralPub = base64Decode(ephemeralPubB64);
    expect(
      ephemeralPub.length,
      32,
      reason: 'X25519 public keys are 32 bytes. If your base64 decodes '
          'to something else, the fixture or the encoding layer is wrong.',
    );
  });

  test('decrypt with wrong session_id → AES-GCM auth fails', () async {
    final priv = _hexToBytes(phoneStaticPrivHex);
    final ephemeralPub = Uint8List.fromList(base64Decode(ephemeralPubB64));
    final encryptedSecret = Uint8List.fromList(base64Decode(encryptedSecretB64));
    final wrongSessionId = Uint8List(16); // all zeros — definitely wrong

    expect(
      () => _phoneDecryptHandshake(
        phoneStaticPriv: priv,
        sessionId: wrongSessionId,
        ephemeralPub: ephemeralPub,
        encryptedSecret: encryptedSecret,
      ),
      throwsA(isA<SecretBoxAuthenticationError>()),
      reason: 'Wrong session_id produces a different HKDF salt → different '
          'session_key → AES-GCM auth tag check fails. This is the defense '
          'against replay/copy-paste of a handshake response.',
    );
  });

  test('decrypt with wrong phone priv → AES-GCM auth fails', () async {
    final wrongPriv = Uint8List(32); // all-zeros — guaranteed wrong
    final sessionId = _hexToBytes(sessionIdHex);
    final ephemeralPub = Uint8List.fromList(base64Decode(ephemeralPubB64));
    final encryptedSecret = Uint8List.fromList(base64Decode(encryptedSecretB64));

    expect(
      () => _phoneDecryptHandshake(
        phoneStaticPriv: wrongPriv,
        sessionId: sessionId,
        ephemeralPub: ephemeralPub,
        encryptedSecret: encryptedSecret,
      ),
      throwsA(isA<SecretBoxAuthenticationError>()),
      reason: 'Wrong private key produces a different X25519 shared secret '
          '→ different session_key → AES-GCM auth tag check fails. This '
          'is the defense against the attacker substituting their own key.',
    );
  });

  test('HMAC-SHA256 of empty body matches Rust fixture', () async {
    final sessionSecret = _hexToBytes(sessionSecretHex);
    final hmac = Hmac.sha256();
    final mac = await hmac.calculateMac(
      Uint8List(0),
      secretKey: SecretKey(sessionSecret),
    );
    final computed = base64Encode(mac.bytes);
    expect(
      computed,
      hmacEmptyBodyB64,
      reason: 'Per-request HMAC binding must match between Rust and Dart '
          'for the same key + body. If this fails, the wire-level '
          'request authentication (X-Miracle-Pair-Session header) is '
          'broken.',
    );
  });
}
